### ISSUE TITLE
May be use this solution for old IE

### ISSUE THREAD

**Issue by evilebottnawi** [postcss/postcss-color-rgba-fallback#15]
```css
background: rgba(255, 255, 255, 0.3);
filter: progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr='#4cffffff', endColorstr='#4cffffff'); /* IE *
```

https://stackoverflow.com/questions/3975688/css-background-opacity-with-rgba-not-working-in-ie-8

**Comment by magsout** [comment]
It is a fallback and it workds, but the value is non-standard, this is a function of Microsoft. So I am not in favor of adding this fallback.

**Comment by pascalduez** [comment]
Hello,

I understand your concerns about proprietary stuff. 
But do we need to write yet another plugin to be able to achieve this ? Feels a bit sad. 
Would allowing it thought an option be more acceptable ?

**Comment by magsout** [comment]
Ok let's do that. Feel free to send a PR

**Comment by evilebottnawi** [comment]
@pascalduez you write code and test?

**Comment by pascalduez** [comment]
Yeah, I'll try to tackle this today.

**Comment by evilebottnawi** [comment]
@pascalduez :+1:

**Comment by magsout** [comment]
released
