### ISSUE TITLE
Fallback for border-bottom color or similar attributes(top,left,right,bottom)

### ISSUE THREAD

**Issue by Gonzalo2683** [postcss/postcss-color-rgba-fallback#19]
Hi, interesting plugin, I tried to use for example:
border-bottom: 1px solid rgba(12,21,34,.5);
It did not work, it is this intentionally so?

**Comment by TrySound** [comment]
@Gonzalo2683  You can set them manually with https://github.com/postcss/postcss-color-rgba-fallback#properties

**Comment by magsout** [comment]
The plugin uses this list to add fallbacks https://github.com/postcss/postcss-color-rgba-fallback/blob/master/index.js#L15.
