### ISSUE TITLE
Allow a background color to be used instead

### ISSUE THREAD

**Issue by jonathanKingston** [postcss/postcss-color-rgba-fallback#23]
Using this has given mixed results for older browsers due to it cutting away the alpha channel and discarding it.

I would like to propose an option where the user can use a base color to aid the transform. This so far (certainly for my use-cases) has yielded nicer results.

So with a white background:
```
body {
  background: #ade4ad;
  background: rgba(153, 221, 153, 0.8);
  font-size:1px;
  border: solid 1px #d1d1d1;
  border: solid 1px rgba(100,102,103,.3);
  color: #999999;
  color: rgba(0, 0, 0, .4);
}
```

Instead of:
```
body {
  background: #99dd99;
  background: rgba(153, 221, 153, 0.8);
  font-size:1px;
  border: solid 1px #646667;
  border: solid 1px rgba(100,102,103,.3);
  color: #000000;
  color: rgba(0, 0, 0, .4);
}
```

**Comment by jonathanKingston** [comment]
@magsout is this something that could be considered? Thanks.

**Comment by magsout** [comment]
@jonathanKingston thanks for your proposal. I never needed it, but why not.

**Comment by jonathanKingston** [comment]
This is visible on https://www.cyber-ami.com if you needed to see it in practice. 
```
ba-focus-panel{background:#f7f7f7;background:rgba(35,35,35,.036);}
```

Instead of:
```
ba-focus-panel{background:#232323;background:rgba(35,35,35,.036);}
```

**Comment by magsout** [comment]
Yes, seems fair
