### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by Semigradsky** [postcss/postcss-color-rgba-fallback#29]
Hi! Could smb publish new release? Looks I haven't permissions for publish new npm package version. @magsout @TrySound @MoOx

**Comment by MoOx** [comment]
@Semigradsky what is your npm username again?

**Comment by MoOx** [comment]
Found it, you have been added on npm!

**Comment by Semigradsky** [comment]
@MoOx `semigradsky`
Cool, thanks! I see this package in my packages list, but still getting 403 forbidden.
It seems I just need to wait.
