### ISSUE TITLE
Already in postcss-color-hex

### ISSUE THREAD

**Issue by ai** [postcss/postcss-color-rgba-fallback#3]
Hi. Thanks for new plugin, but this functionality already exist in [postcss-color-hex](https://github.com/TrySound/postcss-color-hex).

Does this plugin has any changes?

/cc @magsout

**Comment by TrySound** [comment]
+1

**Comment by MoOx** [comment]
This plugin have a clear name pn what it does. And it does not add fallback if there is no need.
We do not know about the other one that have a shitty name (sorry).

**Comment by ai** [comment]
Maybe it will be better to rename TrySound’s plugin?

**Comment by TrySound** [comment]
@ai @MoOx postcss-color-rgb-fallback?

**Comment by ai** [comment]
@TrySound @MoOx yeap, it was more fair to merge projects and use `postcss-color-rgb-fallback` name.

I understand that @MoOx may miss `postcss-color-hex`, but PostCSS org hosted projects is a official. And forking without a reason is a bad practice for official plugins.

**Comment by magsout** [comment]
I haven't forked at all. I hadn't seen his plugin for the same reasons as @MoOx .

**Comment by ai** [comment]
@magsout yeap, I understand the source of problem. Let’s think about solution :).

**Comment by magsout** [comment]
I'll discuss it with @MoOx (move, merge or anything else)  because `postcss-color-rgba-fallback` is used by `cssnext`, so I don't want to break anything on that side.

**Comment by shinnn** [comment]
I totally agree with @MoOx and don't think they should be merged.

**Comment by ai** [comment]
At least `postcss-hex-color` works faster, because it doesn’t use RegExp.

We had only 10 plugins in “Fallback” section. I don’t see any problem to find that this plugin is already implemented. So it is not a problem of `postcss-hex-color`’s author.

And your behavior seems like rough and unfair to me.

**Comment by magsout** [comment]
>At least postcss-hex-color works faster, because it doesn’t use RegExp.

We are talking about what ? Quality of code ? Or just try to fix an issue about two plugins ?

>We had only 10 plugins in “Fallback” section. I don’t see any problem to find that this plugin is already implemented. So it is not a problem of postcss-hex-color’s author.

Yes my bad, I discussed with @MoOx  to add a fallback to rgba for ie8 on cssnext, I didn't check the list on postcss. I'm sorry. So i wrote a plugin and that's all...

**Comment by ai** [comment]
@magsout issue about two plugins

**Comment by ai** [comment]
@magsout I suggested to megre projects. Give a @TrySound access to get best parts from it plugin.

**Comment by MoOx** [comment]
Maybe it's faster but it doesn't handle existing feature.
That said, I don't care who does why.
I don't read postcss plugin list because not everyone push their plugin in this list, I use npm registry with keywords. And -color-hex is not clear at all that's it :)
I don't care who got access to what, because we just all want the same thing: code that works :)
@TrySound have now access to the org.

Reminder: I created this org for this reason ;)

@TrySound I think you should improve this plugin and deprecate on npm the other one that got an unclear name.
@magsout can you give npm access to some others like @TrySound, and me ? (my npm login is moox)

**Comment by ai** [comment]
I think “fast search” is bad for PostCSS ecosystem. I saw many times same plugins in Gulp ecosystem and it confused me, because I have no way to find difference.

**Comment by MoOx** [comment]
Sorry but when you get nothing here https://www.npmjs.com/search?q=postcss%20rgba%20fallback you just do something :)

**Comment by MoOx** [comment]
ALso, color-hex has not automated tests nor Travis, so it's clearly not superior (@TrySound no offence).
I am guessing we should iterated on this one, now color-hex author can ;)

**Comment by TrySound** [comment]
@MoOx I don't want to debate. Agree, I haven't tests. And I unpublished postcss-color-hex
Will improve this one by my experience.

**Comment by MoOx** [comment]
@TrySound sound good !

**Comment by magsout** [comment]
> @magsout can you give npm access to some others like @TrySound, and me ? (my npm login is moox)

Done

**Comment by MoOx** [comment]
Thanks @magsout !
