### ISSUE TITLE
submit a bug

### ISSUE THREAD

**Issue by rguanghui** [postcss/postcss-color-rgba-fallback#6]
hi,

when i use `require('postcss-color-rgba-fallback').postcss` in gruntfile, it give me `undefined is not a function`

hope fixed it, thanks

**Comment by TrySound** [comment]
@magsout We need to use PostCSS plugin API

**Comment by ai** [comment]
PostCSS Plugin Guidelines are mandatory right now. Because all of rules are about ecosystem health.

**Comment by rguanghui** [comment]
@ai 

YES!

英语差，给你们点赞好了。 :+1: :jack_o_lantern:

**Comment by ai** [comment]
@rguanghui no problem, my English is very bad too :D

**Comment by TrySound** [comment]
@rguanghui Published new version. U can use it.

**Comment by rguanghui** [comment]
ok, :100:
